/+
+               Copyright 2025 Aya Partridge
+ Distributed under the Boost Software License, Version 1.0.
+     (See accompanying file LICENSE_1_0.txt or copy at
+           http://www.boost.org/LICENSE_1_0.txt)
+/
module ntropy;

private{
	//Use `arc4random_buf`
	enum useARC4RandomBuf = (){
		version(OpenBSD) return true;
		else return false;
	}();
	
	//Use `getrandom`
	enum useGetrandom = (){
		version(linux) return true;
		else version(Android) return true; //<—— redundant due to `version(linux)`?
		else version(FreeBSD) return true;
		else version(NetBSD) return true;
		else version(DragonFlyBSD) return true;
		else version(Solaris) return true;
		else version(Hurd) return true; //<—— redundant due to `version(linux)`?
		else version(Cygwin) return true;
		else return false;
	}();
	
	//Use the CommonCrypto functionality embedded into `libSystem`.
	enum useCommonCrypto = (){
		version(OSX) return true;
		else version(iOS) return true;
		else version(TVOS) return true;
		else version(WatchOS) return true;
		else version(VisionOS) return true;
		else return false;
	}();
	
	//Use `Bcrypt.h` from the Win32 API.
	enum useBcrypt = (){
		version(Windows) return true;
		else return false;
	}();
	
	//Use `/dev/urandom`.
	enum useDevURandom = (){
		version(AIX) return true;
		else version(Haiku) return true;
		else return false;
	}();
	
	static if(useGetrandom || useDevURandom){
		enum maxSafeBufLength = (){
			version(linux) return 256;
			else version(FreeBSD) return 256;
			else version(NetBSD) return 256;
			else version(DragonFlyBSD) return 256;
			else version(Solaris) return 133_120;
			else return 256;
		}();
	}
	
	static if(useARC4RandomBuf){
		extern(C) void arc4random_buf(void* buf, size_t nBytes) nothrow @nogc;
	}
	static if(useGetrandom){
		extern(C) ptrdiff_t getrandom(void* buf, size_t bufLen, uint flags) nothrow @nogc;
	}
	static if(useCommonCrypto){
		alias CCRNGStatus = int;
		enum kCCSuccess = 0;
		
		extern(C) CCRNGStatus CCRandomGenerateBytes(void* bytes, size_t count) nothrow @nogc;
	}
	static if(useBcrypt){
		import core.sys.windows.subauth: STATUS_SUCCESS;
		import core.sys.windows.ntdef: NTSTATUS;
		
		enum BCRYPT_USE_SYSTEM_PREFERRED_RNG = 0x00000002;
		
		pragma(lib, "bcrypt");
		extern(C) NTSTATUS BCryptGenRandom(void* hAlgorithm, ubyte* pbBuffer, ulong cbBuffer, ulong dwFlags) nothrow @nogc;
	}
	static if(useDevURandom){
		void[] generateDevURandom(return scope void[] buf) nothrow @nogc @trusted{
			import core.stdc.stdio, core.stdc.errno;
			tryAgain:
			auto urandom = fopen("/dev/urandom", "r");
			if(urandom){
				scope(exit) fclose(urandom);
				
				size_t ind = 0;
				fillBuf: do{
					import std.algorithm.comparison: min;
					const wantLen = min(buf.length - ind, maxSafeBufLength);
					const gotLen = fread(&buf[ind], 1, wantLen, urandom);
					if(gotLen < wantLen){
						void resetPosition(){
							import core.stdc.config: c_long;
							tryAgain:
							auto status = fseek(urandom, cast(c_long)ind, SEEK_SET);
							if(status == 0) return;
							assert(status == -1, "Unknown status returned from `fseek`");
							switch(errno){
								case EAGAIN: goto tryAgain;
								case EOVERFLOW: assert(0, "Unpresentable offset? Please submit an issue for this");
								default: assert(0, "An unforeseeable error has occurred! Please submit an issue for this");
							}
						}
						
						if(feof(urandom)){ //did we just hit EOF? (read too many bytes)
							resetPosition();
							continue;
						}
						switch(errno){
							case EAGAIN, EINTR: resetPosition(); continue;
							case ENOMEM: return null;
							default: assert(0, "An unforeseeable error has occurred! Please submit an issue for this");
						}
					}
					ind += gotLen;
				}while(ind < buf.length);
				return buf;
			}else switch(errno){
				case EMFILE: return null; //the max number of file descriptors are already open
				case EINTR: goto tryAgain; //the call was interrupted, so try just again
				case ENOMEM: return null; //we have no memory
				case EACCES: assert(0, "Access denied to `/dev/urandom`? Please submit an issue for this");
				case ENOENT: assert(0, "Your system version doesn't seem to have `/dev/urandom`. Please submit an issue for this");
				default: assert(0, "An unforeseeable error has occurred! Please submit an issue for this");
			}
		}
	}
}

/**
Fills a buffer with data generated by a cryptographically secure pseudorandom number generator. Zero-length buffers are ignored.

This call may block for some time if the requested buffer size is too large (usually if it is more than 256 bytes).
Requesting multiple kilobytes of random data without any pause is not recommended because it may consume all available
entropy on some systems, potentially leading to poor-quality output.

Params:
	buf = A buffer to be filled with cryptographically secure random data.

Returns: `buf`, or `null` if an unexpected error occurred.
*/
void[] generate(return scope void[] buf) nothrow @nogc @safe{
	if(buf.length){
		static if(useARC4RandomBuf){
			() @trusted{ arc4random_buf(&buf[0], buf.length); }();
		}else static if(useGetrandom){
			enum errorStatus = (){
				version(Solaris) return 0;
				else return -1;
			}();
			size_t ind = 0;
			fillBuf: do{
				import std.algorithm.comparison: min;
				const status = (() @trusted => getrandom(&buf[ind], min(buf.length - ind, maxSafeBufLength), 0))();
				import core.stdc.errno;
				if(status == errorStatus) switch(errno){
					case EINTR: continue fillBuf; //the call was interrupted, so just try again
					case EFAULT: return null; //provided address was OOB or invalid
					case EAGAIN: assert(0, "`getrandom` failed with `EAGAIN` even though it should've just blocked? Please submit an issue for this");
					case EINVAL: assert(0, "Your system doesn't support the combination of flags used for `getrandom`. Please submit an issue for this");
					case ENOSYS: assert(0, "Your system version doesn't support `getrandom`. Please submit an issue for this");
					default: assert(0, "An unforeseeable error has occurred! Please submit an issue for this");
				}
				ind += status;
			}while(ind < buf.length);
			return buf;
		}else static if(useCommonCrypto){
			auto status = (() @trusted => CCRandomGenerateBytes(&buf[0], buf.length))();
			assert(status == kCCSuccess);
			return buf;
		}else static if(useBcrypt){
			auto status = (() @trusted => BCryptGenRandom(null, cast(ubyte*)&buf[0], buf.length, BCRYPT_USE_SYSTEM_PREFERRED_RNG))();
			assert(status == STATUS_SUCCESS);
			return buf;
		}else static if(useDevURandom){
			return generateDevURandom(buf);
		}else static assert(0, "Unsupported platform! Please submit a pull request to add support for your platform");
	}
	return buf;
}
unittest{
	import core.stdc.stdlib;
	enum len = 512;
	auto a = malloc(len)[0..len];
	auto b = malloc(len)[0..len];
	auto nSamples = 0;
	auto total = 0;
	foreach(i; 0..256){
		const genA = generate(a);
		const genB = generate(b);
		version(D_BetterC){
		}else if(i >= 256-16){
			import std.format, std.stdio;
			string genAFmt, genBFmt;
			foreach(data; cast(ubyte[])genA) genAFmt ~= "%02X ".format(data);
			foreach(data; cast(ubyte[])genB) genBFmt ~= "%02X ".format(data);
			writefln!"genA: %s\ngenB: %s"(genAFmt, genBFmt);
		}
		assert(genA.length == len && genB.length == len);
		assert(genA[] != genB[]);
	}
}

/**
Returns: a value populated with data generated by a cryptographically secure pseudorandom number generator.

Params:
	success = Set to `true` only on success.

When this function fails (i.e. `success == false`), its return value is undefined (but will most likely be `T.init`).
*/
T generate(T)(out bool success) nothrow @nogc @trusted
if(!__traits(isStaticArray, T) && !is(T == class) && !__traits(isFloating, T) && !is(T == bool)){
	T val;
	if(generate((cast(void*)&val)[0..T.sizeof]) !is null)
		success = true;
	return val;
}
unittest{
	bool success;
	
	auto int1 = generate!int(success); assert(success);
	auto int2 = generate!int(success); assert(success);
	assert(int1 != int2);
	
	cast(void)generate!ubyte(success);  assert(success);
	cast(void)generate!byte(success);   assert(success);
	cast(void)generate!ushort(success); assert(success);
	cast(void)generate!short(success);  assert(success);
	cast(void)generate!uint(success);   assert(success);
	cast(void)generate!ulong(success);  assert(success);
	cast(void)generate!long(success);   assert(success);
	cast(void)generate!char(success);   assert(success);
	cast(void)generate!wchar(success);  assert(success);
	cast(void)generate!dchar(success);  assert(success);
	struct X{ int a; long b; ubyte[8] c; }
	cast(void)generate!X(success); assert(success);
}

/**
Returns: a static array populated with data generated by a cryptographically secure pseudorandom number generator.

Params:
	success = Set to `true` only on success.

When this function fails (i.e. `success == false`), its return value is undefined (but will most likely be `T.init`).
*/
A generate(A: T[n], T, size_t n)(out bool success) nothrow @nogc @safe
if(!is(T == class) && !__traits(isFloating, T) && !is(T == bool)){
	A arr;
	if(generate(arr[]) !is null)
		success = true;
	return arr;
}
unittest{
	bool success;
	
	auto arr1 = generate!(int[4])(success);
	assert(success);
	auto arr2 = generate!(int[4])(success);
	assert(success);
	assert(arr1[] != arr2[]);
}

/**
Returns: a static array of booleans populated with data generated by a cryptographically secure pseudorandom number generator.

Params:
	success = Set to `true` only on success.

When this function fails (i.e. `success == false`), its return value is undefined (but will most likely be `T.init`).
*/
A generate(A: T[n], T: bool, size_t n)(out bool success) nothrow @nogc @safe{
	ubyte[n/8 + (n%8 >= 1)] arr;
	if(generate(arr[]) !is null)
		success = true;
	bool[n] bArr;
	static foreach(byteInd; 0..n/8){{
		enum byteBitInd = byteInd*8;
		static foreach(bitInd; 0..7){
			bArr[byteBitInd + bitInd] = (arr[byteInd] & 1) != 0;
			arr[byteInd] >>= 1;
		}
		bArr[byteBitInd + 7] = (arr[byteInd] & 1) != 0;
	}}
	static foreach_reverse(bitInd; 0..n%8){
		bArr[$-1 - bitInd] = (arr[$-1] & 1) != 0;
		arr[$-1] >>= 1;
	}
	return bArr;
}
unittest{
	bool success;
	
	auto arr1 = generate!(bool[16])(success);
	assert(success);
	auto arr2 = generate!(bool[13])(success);
	assert(success);
	version(D_BetterC){
	}else{
		import std.stdio;
		writefln!"arr1: %s\narr2: %s"(arr1, arr2);
	}
}
